name: jatri_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  upgrader: ^10.3.0
  get:
  hexcolor:
  flutter_screenutil: ^5.9.0
  carousel_slider: ^5.1.1
  pinput:
  flutter_animate: ^4.5.2
  google_fonts:
  ionicons:  
  intl:  
  hive_flutter:
  otp_text_field: ^1.1.3
  flutter_expandable_fab: ^2.3.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
#  flutter_youtube_view: ^2.0.4
  google_maps_flutter: ^2.0.7
  google_maps_webservice: ^0.0.15
  dot_navigation_bar: ^1.0.2
  flashy_tab_bar2: ^0.0.6
  sidebarx: ^0.16.3
  flutter_snake_navigationbar: ^0.6.1
  youtube_player_flutter: ^8.1.1
  change_app_package_name: ^1.1.0
  firebase_core:
  firebase_messaging:
  get_storage:
  badges: ^3.1.2
  flutter_local_notifications: ^17.0.0
  vibration: ^1.7.2
  lottie:
  icons_launcher: ^2.1.7
  facebook_app_events: ^0.20.0
  introduction_screen:
#  flutter_launcher_icons: ^0.13.1
#  archive: ^3.4.10
icons_launcher:
  image_path: "assets/ic_logo_border.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 
  build_runner:




flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
