// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1bCTqKgW7M7NeeWxb58YeIeAFRlBgzY',
    appId: '1:60676382250:web:f3bee64bf271ae50f3ed53',
    messagingSenderId: '60676382250',
    projectId: 'astha-care-giver',
    authDomain: 'astha-care-giver.firebaseapp.com',
    storageBucket: 'astha-care-giver.firebasestorage.app',
    measurementId: 'G-RDB9JMNNY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3vtxNKOtreDmPwKbcNUIgu8FC4cpDVU',
    appId: '1:60676382250:android:2964818541805810f3ed53',
    messagingSenderId: '60676382250',
    projectId: 'astha-care-giver',
    storageBucket: 'astha-care-giver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCE9ne5-z4OUPeLWV4H3hc-OzvZC4z-Y',
    appId: '1:60676382250:ios:9983d54cd7043a31f3ed53',
    messagingSenderId: '60676382250',
    projectId: 'astha-care-giver',
    storageBucket: 'astha-care-giver.firebasestorage.app',
    iosBundleId: 'com.quicktechit.asthacaregiver.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVCE9ne5-z4OUPeLWV4H3hc-OzvZC4z-Y',
    appId: '1:60676382250:ios:44d3df0186dce840f3ed53',
    messagingSenderId: '60676382250',
    projectId: 'astha-care-giver',
    storageBucket: 'astha-care-giver.firebasestorage.app',
    iosBundleId: 'com.example.drutoSheba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1bCTqKgW7M7NeeWxb58YeIeAFRlBgzY',
    appId: '1:60676382250:web:f1a1ee7198bd4a30f3ed53',
    messagingSenderId: '60676382250',
    projectId: 'astha-care-giver',
    authDomain: 'astha-care-giver.firebaseapp.com',
    storageBucket: 'astha-care-giver.firebasestorage.app',
    measurementId: 'G-1MR8MG8G4W',
  );

}