// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJqMOZfWVrg5015K7KZ-LhZXeecPIFmYA',
    appId: '1:816144966935:web:d985d17d59dca2992e8352',
    messagingSenderId: '816144966935',
    projectId: 'gari-lagbee',
    authDomain: 'gari-lagbee.firebaseapp.com',
    storageBucket: 'gari-lagbee.firebasestorage.app',
    measurementId: 'G-YXXZVFMWQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMiwy7h4Zp6KHoQSONr6SqqR-4K1qQ5Y',
    appId: '1:816144966935:android:de3c1297da1cba952e8352',
    messagingSenderId: '816144966935',
    projectId: 'gari-lagbee',
    storageBucket: 'gari-lagbee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNqnUNSXvoheCFiGTxJKecQmhS4JXO1Zc',
    appId: '1:816144966935:ios:e1974abcfd6b02912e8352',
    messagingSenderId: '816144966935',
    projectId: 'gari-lagbee',
    storageBucket: 'gari-lagbee.firebasestorage.app',
    iosBundleId: 'com.quicktechit.garilagbee.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNqnUNSXvoheCFiGTxJKecQmhS4JXO1Zc',
    appId: '1:816144966935:ios:3fbcc55caebe37972e8352',
    messagingSenderId: '816144966935',
    projectId: 'gari-lagbee',
    storageBucket: 'gari-lagbee.firebasestorage.app',
    iosBundleId: 'com.example.drutoSheba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJqMOZfWVrg5015K7KZ-LhZXeecPIFmYA',
    appId: '1:816144966935:web:01b7ad875bdca5382e8352',
    messagingSenderId: '816144966935',
    projectId: 'gari-lagbee',
    authDomain: 'gari-lagbee.firebaseapp.com',
    storageBucket: 'gari-lagbee.firebasestorage.app',
    measurementId: 'G-6E4RXDHE9G',
  );
}
